services:
  actual_server:
    image: actualbudget/actual-server:latest
    container_name: actual-budget-wife
    restart: unless-stopped
    volumes:
      - ./data:/data
    env_file:
      - .env
    networks:
      - cloudflare-network # http://actual-budget-wife:5006

networks:
  cloudflare-network:
    external: true